[package]
name = "tutorial4_buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if.workspace = true 
env_logger.workspace = true 
winit.workspace = true 
log.workspace = true 
wgpu.workspace = true 
pollster.workspace = true
bytemuck.workspace = true
